// Code Generated by Sidekick is for learning and experimentation purposes only.

// middleware/apiKey.js
import supabase from '../config/database.js';  // ← Use shared client!

export const apiKeyMiddleware = async (req, res, next) => {
  try {
    console.log(`🔐 Middleware triggered for: ${req.method} ${req.path}`);

    const apiKey = req.headers['x-api-key'];

    if (!apiKey) {
      console.log('❌ No API key provided');
      return res.status(401).json({
        success: false,
        error: 'API key is required'
      });
    }

    console.log(`🔑 API Key received: ${apiKey}`);

    // Query clients table using SHARED client
    const { data: client, error } = await supabase
      .from('clients')
      .select('id, company_name, api_key, website_url')
      .eq('api_key', apiKey)
      .single();

    console.log('🔍 Query result:', { client, error });

    if (error || !client) {
      console.log('❌ Invalid or inactive API key');
      return res.status(401).json({
        success: false,
        error: 'Invalid or inactive API key'
      });
    }

    console.log(`✅ API Key validated for client: ${client.company_name} (ID: ${client.id})`);

    req.clientId = client.id;
    req.clientName = client.company_name;

    console.log(`✅ req.clientId set to: ${req.clientId}`);

    next();

  } catch (error) {
    console.error('❌ Middleware error:', error);
    res.status(500).json({
      success: false,
      error: 'Authentication failed'
    });
  }
};
