// Code Generated by Sidekick is for learning and experimentation purposes only.

// middleware/apiKey.js
import supabase from '../config/database.js';  // ← Use shared client!

export const apiKeyMiddleware = async (req, res, next) => {
  try {
    console.log(`🔐 Middleware triggered for: ${req.method} ${req.path}`);

    const apiKey = req.headers['x-api-key']?.trim();

    if (!apiKey) {
      console.log('❌ No API key provided');
      return res.status(401).json({
        success: false,
        error: 'API key is required'
      });
    }

    console.log(`🔑 API Key received: ${apiKey}`);

    // Query clients table using SHARED client
    try {
      const { data: client, error } = await supabase
        .from('clients')
        .select('id, company_name, api_key, website_url, starter_suggestions')
        .eq('api_key', apiKey)
        .single();

      if (error) {
        console.error('❌ Supabase query error:', {
          message: error.message,
          code: error.code,
          hint: error.hint,
          details: error.details
        });
        return res.status(401).json({
          success: false,
          error: 'Invalid or inactive API key',
          debug: error.message
        });
      }

      if (!client) {
        console.log('❌ Invalid or inactive API key');
        console.log(`   Expected key format: "${apiKey}"`);
        console.log(`   Key length: ${apiKey.length}`);
        return res.status(401).json({
          success: false,
          error: 'Invalid or inactive API key'
        });
      }

      console.log(`✅ API Key validated for client: ${client.company_name} (ID: ${client.id})`);

      req.clientId = client.id;
      req.clientName = client.company_name;

      console.log(`✅ req.clientId set to: ${req.clientId}`);

      next();
    } catch (queryError) {
      console.error('❌ API key query error:', {
        message: queryError.message,
        stack: queryError.stack
      });
      return res.status(500).json({
        success: false,
        error: 'Authentication service error',
        debug: queryError.message
      });
    }

  } catch (error) {
    console.error('❌ Middleware error:', error);
    res.status(500).json({
      success: false,
      error: 'Authentication failed'
    });
  }
};
