import express from 'express';
import OpenAI from 'openai';
import supabase from '../config/database.js';
import { embeddingService } from '../services/openaiService.js';
import { vectorSearchService } from '../services/vectorSearchService.js';
import { linkConversationToLead } from '../services/leadsService.js';

const router = express.Router();
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// GET /api/chat/history/:conversationId - Fetch conversation history
// Auth: X-API-Key header (client API key)
// Middleware automatically extracts client_id from the API key
router.get('/history/:conversationId', async (req, res) => {
  try {
    const { conversationId } = req.params;

    console.log(`📜 Fetching history for conversation ${conversationId} (client: ${req.clientId})`);

    // 1. Verify conversation belongs to this client
    const { data: conversation, error: convError } = await req.supabaseClient
      .from('conversations')
      .select('id, client_id, visitor_id, status')
      .eq('id', conversationId)
      .eq('client_id', req.clientId)  // ✅ Security: Only return conversations for this client
      .single();

    if (convError || !conversation) {
      console.log(`❌ Conversation ${conversationId} not found for client ${req.clientId}`);
      return res.status(404).json({
        error: 'Conversation not found',
        messages: []
      });
    }

    // 2. Get messages from this conversation
    const { data: messages, error: msgError } = await req.supabaseClient
      .from('messages')
      .select('id, role, content, created_at')
      .eq('conversation_id', conversationId)
      .order('created_at', { ascending: true });

    if (msgError) {
      console.error('❌ Error fetching messages:', msgError);
      return res.status(500).json({
        error: 'Failed to fetch messages',
        messages: []
      });
    }

    console.log(`✅ Found ${messages?.length || 0} messages for conversation ${conversationId}`);

    // 3. Return in format frontend expects
    res.json({
      conversationId: conversation.id,
      visitorId: conversation.visitor_id,
      status: conversation.status,
      messages: messages || []
    });

  } catch (error) {
    console.error('❌ History fetch error:', error);
    res.status(500).json({
      error: 'Failed to fetch conversation history',
      messages: []
    });
  }
});

// POST /api/chat/ - Handle incoming chat message
// Auth: X-API-Key header (client API key)
// Middleware automatically extracts client_id from the API key
router.post('/', async (req, res) => {
  try {
    const { message, visitorId } = req.body;

    console.log(`\n💬 Message from visitor ${visitorId}`);

    // Validate required fields
    if (!message || !visitorId) {
      return res.status(400).json({
        error: 'Missing required fields: message, visitorId'
      });
    }

    // ✅ Get client info
    const { data: client } = await req.supabaseClient
      .from('clients')
      .select('company_name, website_url')
      .eq('id', req.clientId)
      .single();

    console.log(`👤 Client: ${client?.company_name || 'Unknown'} (ID: ${req.clientId})`);
    console.log(`📝 Message: "${message}"`);

    // 1. Find or create conversation
    let conversation = await findOrCreateConversation(req.supabaseClient, req.clientId, visitorId);

    // 1.5. 🔗 NEW: Link conversation to existing lead if not already linked
    try {
      const { data: existingLead, error: leadError } = await req.supabaseClient
        .from('leads')
        .select('id, conversation_id')
        .eq('client_id', req.clientId)
        .eq('visitor_id', visitorId)
        .maybeSingle();

      if (existingLead && !existingLead.conversation_id) {
        console.log(`🔗 Linking conversation ${conversation.id} to existing lead ${existingLead.id}`);
        await linkConversationToLead(req.supabaseClient, existingLead.id, conversation.id);
      }
    } catch (leadLinkError) {
      console.error('⚠️ Failed to link conversation to lead:', leadLinkError.message);
      // Don't fail the chat request if lead linking fails - it's non-critical
    }

    // 2. Save user message
    await saveMessage(req.supabaseClient, conversation.id, 'user', message);

    // 3. RAG: Search for relevant context
    console.log('🔍 Searching knowledge base...');
    let contextSources = [];
    let ragContext = '';

    try {
      const embeddingResult = await embeddingService.generateEmbedding(message);

      if (embeddingResult.success) {
        const searchResult = await vectorSearchService.searchSimilarChunks(
          embeddingResult.embedding,
          req.clientId,  // ✅ Pass clientId here
          {
            matchThreshold: 0.4,
            matchCount: 5
          }
        );

        // Code Generated by Sidekick is for learning and experimentation purposes only.

        // In chatRoutes.js, inside the RAG section, add detailed logging:

        if (searchResult.success && searchResult.results.length > 0) {
          console.log(`✅ Found ${searchResult.results.length} relevant sources`);

          // 🔍 NEW: Log EXACT chunks being used
          searchResult.results.forEach((result, i) => {
            console.log(`\n📄 Chunk ${i + 1}:`);
            console.log(`   URL: ${result.url}`);
            console.log(`   Similarity: ${result.similarity}`);
            console.log(`   Chunk ID: ${result.id || 'N/A'}`);  // Add this
            console.log(`   Full Text:\n   ${result.text}`);    // Show FULL text
            console.log('---');
          });

          ragContext = searchResult.results
            .map((result, index) => {
              return `[Source ${index + 1}: ${result.url}]\n${result.text}`;
            })
            .join('\n\n---\n\n');

          // 🔍 NEW: Log the FULL context being sent to OpenAI
          console.log('\n📦 FULL CONTEXT BEING SENT TO OPENAI:');
          console.log('=====================================');
          console.log(ragContext);
          console.log('=====================================\n');

          contextSources = searchResult.results.map(r => ({
            url: r.url,
            similarity: Math.round(r.similarity * 100) / 100
          }));
        }
        else {
          console.log('⚠️ No relevant context found');
        }
      }
    } catch (ragError) {
      console.error('❌ RAG search failed:', ragError.message);
      console.log('⚠️ Continuing without context...');
    }

    // 4. Get conversation history
    const history = await getConversationHistory(req.supabaseClient, conversation.id);

    // 5. Build messages with system prompt
    const companyName = client?.company_name || 'our company';
    const messages = [
      {
        role: 'system',
        content: buildSystemPrompt(companyName, ragContext)
      },
      ...history
    ];

    console.log('🤖 Calling OpenAI...');

    // 6. Call OpenAI
    const completion = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: messages,
      temperature: 0.7,
      max_tokens: 500
    });

    const botResponse = completion.choices[0].message.content;
    console.log('✅ Response generated');

    // 7. Save assistant response
    await saveMessage(req.supabaseClient, conversation.id, 'assistant', botResponse);

    // 8. Return response
    res.json({
      response: botResponse,
      conversationId: conversation.id,
      clientName: companyName,
      ...(contextSources.length > 0 && {
        sources: contextSources,
        contextsUsed: contextSources.length
      })
    });

  } catch (error) {
    console.error('❌ Chat error:', error);

    if (error.response?.status === 401) {
      return res.status(500).json({ error: 'OpenAI API key invalid' });
    }

    res.status(500).json({ error: 'Failed to process message' });
  }
});

// System prompt builder
function buildSystemPrompt(companyName, ragContext) {
  const basePrompt = `You are a helpful AI assistant for ${companyName}.

Your role is to:
- Answer questions about the company's services, expertise, and offerings
- Be friendly, professional, and concise
- If you don't know something, politely say so`;

  if (ragContext && ragContext.trim().length > 0) {
    return `${basePrompt}

Use the following information from the company's website to answer questions:

${ragContext}

Instructions:
- Answer naturally based on the context provided
- Keep responses conversational
- If the context doesn't cover the question, use general knowledge but note they should contact the team for specifics`;
  }

  return basePrompt;
}

// Helper functions
async function findOrCreateConversation(supabaseClient, clientId, visitorId) {
  const { data: existing } = await supabaseClient
    .from('conversations')
    .select('*')
    .eq('client_id', clientId)
    .eq('visitor_id', visitorId)
    .eq('status', 'active')
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (existing) return existing;

  const { data: newConversation, error } = await supabaseClient
    .from('conversations')
    .insert({
      client_id: clientId,
      visitor_id: visitorId,
      status: 'active'
    })
    .select()
    .single();

  if (error) throw error;
  return newConversation;
}

async function saveMessage(supabaseClient, conversationId, role, content) {
  const { error } = await supabaseClient
    .from('messages')
    .insert({
      conversation_id: conversationId,
      role: role,
      content: content
    });

  if (error) throw error;
}

async function getConversationHistory(supabaseClient, conversationId) {
  const { data: messages, error } = await supabaseClient
    .from('messages')
    .select('role, content')
    .eq('conversation_id', conversationId)
    .order('created_at', { ascending: true })
    .limit(20);

  if (error) throw error;

  return messages.map(msg => ({
    role: msg.role,
    content: msg.content
  }));
}

export default router;
