// Code Generated by Sidekick is for learning and experimentation purposes only.

import express from 'express';
import { embeddingService } from '../services/openaiService.js';
import supabase from '../config/database.js'

const router = express.Router();

/**
 * Test embedding generation
 * POST /api/embeddings/test
 * 
 * Auth: 
 * - Client role: Bearer token (dashboard auth) OR X-API-Key
 * - Super admin: X-API-Key REQUIRED (to identify which client to work with)
 */
router.post('/test', async (req, res) => {
    try {
        // Validate authentication and client_id
        if (!req.clientId) {
            return res.status(401).json({
                success: false,
                error: 'X-API-Key header is required for embedding endpoints'
            });
        }

        // For super_admin, require X-API-Key (not Bearer token)
        if (req.userRole === 'super_admin' && req.authType === 'bearer') {
            return res.status(401).json({
                success: false,
                error: 'Super admin users must use X-API-Key header for embedding endpoints'
            });
        }

        const { text } = req.body;

        const result = await embeddingService.testEmbedding(
            text || "This is a test sentence for embedding generation."
        );

        if (result.success) {
            res.json({
                success: true,
                message: 'Embedding generated successfully',
                model: result.model,
                dimensions: result.embedding.length,
                tokens: result.tokens,
                estimatedCost: embeddingService.estimateCost(result.tokens),
                preview: result.embedding.slice(0, 10)
            });
        } else {
            res.status(500).json({
                success: false,
                error: result.error
            });
        }

    } catch (error) {
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

/**
 * Get embedding statistics
 * GET /api/embeddings/stats
 * 
 * Auth: 
 * - Client role: Bearer token (dashboard auth) OR X-API-Key
 * - Super admin: X-API-Key REQUIRED (to identify which client to work with)
 */
router.get('/stats', async (req, res) => {
    try {
        // Validate authentication and client_id
        if (!req.clientId) {
            return res.status(401).json({
                success: false,
                error: 'X-API-Key header is required for embedding endpoints'
            });
        }

        // For super_admin, require X-API-Key (not Bearer token)
        if (req.userRole === 'super_admin' && req.authType === 'bearer') {
            return res.status(401).json({
                success: false,
                error: 'Super admin users must use X-API-Key header for embedding endpoints'
            });
        }

        console.log('📊 Stats endpoint - clientId:', req.clientId, 'role:', req.userRole);

        const pendingResult = await embeddingService.getPendingChunksCount(req.clientId);

        if (!pendingResult.success) {
            return res.status(500).json({
                success: false,
                error: 'Failed to get pending chunks',
                details: pendingResult.error
            });
        }

        // Get total chunks count
        const { count: totalCount, error: totalError } = await supabase
            .from('content_chunks')
            .select('*', { count: 'exact', head: true })
            .eq('client_id', req.clientId);

        if (totalError) {
            console.error('❌ Error getting total count:', totalError);
            return res.status(500).json({
                success: false,
                error: 'Failed to get total chunks count'
            });
        }

        const withEmbeddings = (totalCount || 0) - (pendingResult.count || 0);

        res.json({
            success: true,
            stats: {
                totalChunks: totalCount || 0,
                withEmbeddings,
                pendingEmbeddings: pendingResult.count || 0,
                percentComplete: totalCount > 0
                    ? Math.round((withEmbeddings / totalCount) * 100)
                    : 0
            }
        });

    } catch (error) {
        console.error('❌ Error in /stats endpoint:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to get statistics',
            details: error.message
        });
    }
});

/**
 * Generate embeddings for all pending chunks
 * POST /api/embeddings/generate
 * 
 * Auth: 
 * - Client role: Bearer token (dashboard auth) OR X-API-Key
 * - Super admin: X-API-Key REQUIRED (to identify which client to work with)
 */
router.post('/generate', async (req, res) => {
    try {
        // Validate authentication and client_id
        if (!req.clientId) {
            return res.status(401).json({
                success: false,
                error: 'X-API-Key header is required for embedding endpoints'
            });
        }

        // For super_admin, require X-API-Key (not Bearer token)
        if (req.userRole === 'super_admin' && req.authType === 'bearer') {
            return res.status(401).json({
                success: false,
                error: 'Super admin users must use X-API-Key header for embedding endpoints'
            });
        }

        console.log('🚀 Generate endpoint - clientId:', req.clientId, 'role:', req.userRole);

        console.log(`🔍 Checking pending chunks for client: ${req.clientId}`);

        // Check pending count first
        const pendingResult = await embeddingService.getPendingChunksCount(req.clientId);

        if (!pendingResult.success) {
            console.error('❌ Error getting pending chunks:', pendingResult.error);
            return res.status(500).json({
                success: false,
                error: 'Failed to check pending chunks',
                details: pendingResult.error
            });
        }

        console.log(`📊 Found ${pendingResult.count} chunks needing embeddings`);

        if (pendingResult.count === 0) {
            return res.json({
                success: true,
                message: 'All chunks already have embeddings',
                pendingCount: 0
            });
        }

        // Start processing (this will take time)
        console.log(`🚀 Starting embedding generation for ${pendingResult.count} chunks...`);
        const result = await embeddingService.processAllChunks(req.clientId);

        if (!result.success) {
            console.error('❌ Embedding generation failed:', result.error);
            return res.status(500).json({
                success: false,
                error: 'Failed to generate embeddings',
                details: result.error
            });
        }

        res.json({
            success: true,
            message: 'Embeddings generated successfully',
            totalChunks: result.totalChunks,
            successCount: result.successCount,
            failedCount: result.failedCount,
            totalTokens: result.totalTokens,
            estimatedCost: result.estimatedCost,
            batches: result.batches
        });

    } catch (error) {
        console.error('❌ Error in /generate endpoint:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to generate embeddings',
            details: error.message
        });
    }
});

/**
 * Regenerate embeddings for specific URL
 * POST /api/embeddings/regenerate
 * 
 * Auth: 
 * - Client role: Bearer token (dashboard auth) OR X-API-Key
 * - Super admin: X-API-Key REQUIRED (to identify which client to work with)
 */
router.post('/regenerate', async (req, res) => {
    try {
        // Validate authentication and client_id
        if (!req.clientId) {
            return res.status(401).json({
                success: false,
                error: 'X-API-Key header is required for embedding endpoints'
            });
        }

        // For super_admin, require X-API-Key (not Bearer token)
        if (req.userRole === 'super_admin' && req.authType === 'bearer') {
            return res.status(401).json({
                success: false,
                error: 'Super admin users must use X-API-Key header for embedding endpoints'
            });
        }

        const { url } = req.body;

        if (!url) {
            return res.status(400).json({
                success: false,
                error: 'URL is required'
            });
        }

        // Clear existing embeddings for this URL
        const { error: deleteError } = await supabase
            .from('content_chunks')
            .update({
                embedding: null,
                embedding_model: null,
                embedding_token_count: null,
                embedding_generated_at: null
            })
            .eq('client_id', req.clientId)
            .eq('url', url);

        if (deleteError) throw deleteError;

        // Get chunks for this URL
        const { data: chunks, error: fetchError } = await supabase
            .from('content_chunks')
            .select('id, chunk_text')
            .eq('client_id', req.clientId)
            .eq('url', url)
            .order('chunk_index', { ascending: true });

        if (fetchError) throw fetchError;

        if (!chunks || chunks.length === 0) {
            return res.status(404).json({
                success: false,
                error: 'No chunks found for this URL'
            });
        }

        // Process chunks
        const result = await embeddingService.processChunksBatch(chunks);

        res.json({
            success: true,
            message: 'Embeddings regenerated successfully',
            url,
            ...result
        });

    } catch (error) {
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

export default router;
