// Code Generated by Sidekick is for learning and experimentation purposes only.

import express from 'express';
import supabase from '../config/database.js';

const router = express.Router();

/**
 * GET /api/widget/config
 * Fetch widget configuration using API key
 * 
 * Headers: { 'X-API-Key': 'greeto-xxx' }
 * 
 * Response:
 * {
 *   "success": true,
 *   "client_name": "Acme Corp",
 *   "widget_config": {
 *     "primary_color": "#FF0000",
 *     "secondary_color": "#CC0000",
 *     "position": "bottom-right",
 *     "welcome_message": "Hello!"
 *   }
 * }
 */

router.get('/config', async (req, res) => {
  try {
    // Get API key from header
    const apiKey = req.headers['x-api-key'];

    if (!apiKey) {
      return res.status(400).json({
        success: false,
        error: 'API key is required in X-API-Key header'
      });
    }

    console.log(`🔑 Widget config request for API key: ${apiKey}`);

    // Query client with this API key
    const { data: client, error } = await supabase
      .from('clients')
      .select('id, company_name, website_url, widget_config, status')
      .eq('api_key', apiKey)
      .single();

    if (error || !client) {
      console.log(`❌ Invalid API key: ${apiKey}`);
      return res.status(401).json({
        success: false,
        error: 'Invalid API key'
      });
    }

    // Check if client is active
    if (client.status !== 'active') {
      console.log(`⚠️ Inactive client: ${client.company_name}`);
      return res.status(403).json({
        success: false,
        error: 'Client account is not active'
      });
    }

    // Get widget config (with defaults if null)
    const widgetConfig = client.widget_config || {
      primary_color: '#2563EB',
      secondary_color: '#1E40AF',
      position: 'bottom-right',
      welcome_message: 'Hi! How can we help you today?'
    };

    console.log(`✅ Config loaded for: ${client.company_name}`);

    // Return config
    res.json({
      success: true,
      client_name: client.company_name,
      widget_config: widgetConfig
    });

  } catch (error) {
    console.error('❌ Widget config error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch widget configuration'
    });
  }
});

export default router;
