// Code Generated by Sidekick is for learning and experimentation purposes only.

// services/chunkingService.js

import supabase from "../config/database.js";

class ChunkingService {
  constructor() {
    // IMPROVED CHUNKING - Character-based with sentence boundaries
    this.chunkSize = 800;           // 800 characters per chunk (was 500 words)
    this.overlap = 150;             // 150 character overlap
    this.minChunkSize = 100;        // Minimum chunk size
    this.maxContentLength = 200000; // 200k chars max per page
    
    // HOMEPAGE SPECIFIC
    this.homepageChunkSize = 600;   // Smaller chunks for homepage
    this.homepageOverlap = 100;
    this.homepageMaxLength = 100000; // 100k chars max for homepage
    this.homepageMaxChunks = 50;
  }

  /**
   * Detect if content is from homepage
   */
  isHomepageContent(url) {
    try {
      const urlObj = new URL(url);
      const path = urlObj.pathname;
      const homepagePaths = ['/', '/home', '/index', '/index.html', '/index.php', ''];
      
      const normalizedPath = path.endsWith('/') && path.length > 1 
        ? path.slice(0, -1) 
        : path;
      
      return homepagePaths.includes(normalizedPath) || homepagePaths.includes(path);
      
    } catch (error) {
      return false;
    }
  }

  /**
   * Get chunking parameters based on content type
   */
  getChunkingParams(url) {
    const isHome = this.isHomepageContent(url);
    
    return {
      isHomepage: isHome,
      chunkSize: isHome ? this.homepageChunkSize : this.chunkSize,
      overlap: isHome ? this.homepageOverlap : this.overlap,
      maxContentLength: isHome ? this.homepageMaxLength : this.maxContentLength,
      maxChunks: isHome ? this.homepageMaxChunks : 200,
      label: isHome ? '🏠 HOMEPAGE' : '📄 PAGE'
    };
  }

  /**
   * Pre-process content with content-type awareness
   */
  preprocessContent(text, params) {
    if (!text || text.trim().length === 0) {
      return '';
    }

    // Apply length limit based on page type
    if (text.length > params.maxContentLength) {
      console.log(`⚠️ ${params.label} Content too large (${text.length} chars), truncating to ${params.maxContentLength}`);
      text = text.substring(0, params.maxContentLength);
    }

    // Normalize whitespace
    text = text
      .replace(/\s+/g, ' ')     // Multiple spaces to single space
      .replace(/\n+/g, '\n')    // Multiple newlines to single newline
      .trim();

    return text;
  }

  /**
   * Split text into sentences (better semantic boundaries)
   */
  splitIntoSentences(text) {
    // Match sentences ending with . ! ? followed by space or newline
    // Also handle common abbreviations (Dr., Mr., Mrs., etc.)
    const sentences = text.match(/[^.!?\n]+[.!?\n]+/g) || [];
    
    // If no sentences found, split by newlines or return as single chunk
    if (sentences.length === 0) {
      const lines = text.split('\n').filter(line => line.trim().length > 0);
      return lines.length > 0 ? lines : [text];
    }
    
    return sentences.map(s => s.trim()).filter(s => s.length > 0);
  }

  /**
   * CHARACTER-BASED CHUNKING with sentence boundaries
   * This creates smaller, more focused chunks
   */
  chunkText(text, url) {
    const params = this.getChunkingParams(url);
    
    console.log(`${params.label} Chunking with size=${params.chunkSize} chars, overlap=${params.overlap} chars`);
    
    text = this.preprocessContent(text, params);
    
    if (!text || text.length === 0) {
      return [];
    }

    // Split into sentences first
    const sentences = this.splitIntoSentences(text);
    
    const chunks = [];
    let currentChunk = '';
    let chunkIndex = 0;
    let sentenceIndex = 0;

    for (let i = 0; i < sentences.length; i++) {
      const sentence = sentences[i];
      
      // If adding this sentence would exceed chunk size
      if (currentChunk.length > 0 && 
          (currentChunk.length + sentence.length) > params.chunkSize) {
        
        // Save current chunk if it's substantial
        if (currentChunk.length >= this.minChunkSize) {
          chunks.push({
            text: currentChunk.trim(),
            index: chunkIndex,
            charCount: currentChunk.length,
            startSentence: sentenceIndex,
            endSentence: i
          });
          
          chunkIndex++;
          
          // Check max chunks limit
          if (chunkIndex >= params.maxChunks) {
            console.warn(`⚠️ ${params.label} Reached max chunks (${params.maxChunks}), stopping`);
            break;
          }
        }
        
        // Start new chunk with overlap
        // Take last N characters from previous chunk for context
        const overlapText = currentChunk.length > params.overlap 
          ? currentChunk.slice(-params.overlap) 
          : currentChunk;
        
        currentChunk = overlapText + ' ' + sentence;
        sentenceIndex = i;
        
      } else {
        // Add sentence to current chunk
        currentChunk += (currentChunk.length > 0 ? ' ' : '') + sentence;
      }
    }

    // Don't forget the last chunk
    if (currentChunk.trim().length >= this.minChunkSize) {
      chunks.push({
        text: currentChunk.trim(),
        index: chunkIndex,
        charCount: currentChunk.length,
        startSentence: sentenceIndex,
        endSentence: sentences.length
      });
    }

    console.log(`${params.label} Created ${chunks.length} chunks (avg ${Math.round(text.length / chunks.length)} chars each)`);
    
    return chunks;
  }

  /**
   * Process content with URL context
   */
  async processContent(clientId, url, pageTitle, content) {
    try {
      const params = this.getChunkingParams(url);
      
      if (content.length > 500000) {
        console.log(`⚠️ ${params.label} Large content (${Math.round(content.length / 1000)}KB), may take longer...`);
      }

      // Create chunks with sentence-aware splitting
      const chunks = this.chunkText(content, url);

      if (chunks.length === 0) {
        console.log(`⚠️ No chunks created for ${url} (empty content)`);
        return { success: false, reason: 'empty_content' };
      }

      // Store chunks
      const result = await this.storeChunksWithMetadata(
        clientId, 
        url, 
        pageTitle, 
        chunks, 
        new Date().toISOString()
      );

      // Clear chunks from memory
      chunks.length = 0;

      return result;

    } catch (error) {
      console.error('Error processing content:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Store chunks with metadata
   */
  async storeChunksWithMetadata(clientId, url, pageTitle, chunks, scrapedAt) {
    try {
      if (!chunks || chunks.length === 0) {
        return { success: false, reason: 'no_chunks' };
      }

      const totalChunks = chunks.length;
      
      // Delete existing chunks first
      const { error: deleteError } = await supabase
        .from('content_chunks')
        .delete()
        .eq('client_id', clientId)
        .eq('url', url);

      if (deleteError && deleteError.code !== 'PGRST116') {
        console.log(`⚠️ Delete warning: ${deleteError.message}`);
      }

      // Insert in smaller batches
      const batchSize = 50;
      let insertedCount = 0;

      for (let i = 0; i < chunks.length; i += batchSize) {
        const batch = chunks.slice(i, i + batchSize);
        
        const chunksData = batch.map(chunk => ({
          client_id: clientId,
          url: url,
          page_title: pageTitle,
          chunk_text: chunk.text,
          chunk_index: chunk.index,
          word_count: chunk.text.split(/\s+/).length, // Calculate word count
          source_scraped_at: scrapedAt,
          total_chunks: totalChunks
        }));

        const { error } = await supabase
          .from('content_chunks')
          .insert(chunksData);

        if (error) {
          console.error(`Error inserting batch ${i}-${i + batch.length}:`, error);
          return { success: false, error: error.message };
        }

        insertedCount += batch.length;
      }

      console.log(`✅ Stored ${insertedCount} chunks for ${url}`);
      return { success: true, count: insertedCount };

    } catch (error) {
      console.error('Error in storeChunksWithMetadata:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Get chunks for a specific URL
   */
  async getChunks(clientId, url) {
    try {
      const { data, error } = await supabase
        .from('content_chunks')
        .select('*')
        .eq('client_id', clientId)
        .eq('url', url)
        .order('chunk_index', { ascending: true });

      if (error) throw error;

      return { success: true, chunks: data };

    } catch (error) {
      console.error('Error getting chunks:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Get all chunks for a client
   */
  async getAllChunks(clientId, limit = 100) {
    try {
      let query = supabase
        .from('content_chunks')
        .select('id, url, page_title, chunk_text, chunk_index, word_count, total_chunks, source_scraped_at')
        .eq('client_id', clientId)
        .order('source_scraped_at', { ascending: false })
        .order('url', { ascending: true })
        .order('chunk_index', { ascending: true });

      if (limit) {
        query = query.limit(limit);
      }

      const { data, error } = await query;

      if (error) throw error;

      return { success: true, chunks: data, count: data.length };

    } catch (error) {
      console.error('Error getting all chunks:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Get unique URLs that have been scraped
   */
  async getScrapedUrls(clientId) {
    try {
      const { data, error } = await supabase
        .from('content_chunks')
        .select('url, page_title, source_scraped_at, total_chunks')
        .eq('client_id', clientId)
        .eq('chunk_index', 0)
        .order('source_scraped_at', { ascending: false });

      if (error) throw error;

      return { success: true, urls: data, count: data.length };

    } catch (error) {
      console.error('Error getting scraped URLs:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Get chunk statistics
   */
  async getChunkStats(clientId) {
    try {
      const { data, error } = await supabase
        .from('content_chunks')
        .select('url, page_title, chunk_index, word_count, total_chunks')
        .eq('client_id', clientId);

      if (error) throw error;

      const urlStats = {};
      let totalChunks = 0;
      let totalWords = 0;

      data.forEach(chunk => {
        if (!urlStats[chunk.url]) {
          urlStats[chunk.url] = {
            pageTitle: chunk.page_title,
            chunkCount: 0,
            totalChunks: chunk.total_chunks,
            wordCount: 0
          };
        }
        urlStats[chunk.url].chunkCount++;
        urlStats[chunk.url].wordCount += chunk.word_count || 0;
        totalChunks++;
        totalWords += chunk.word_count || 0;
      });

      return {
        success: true,
        stats: {
          totalUrls: Object.keys(urlStats).length,
          totalChunks,
          totalWords,
          averageWordsPerChunk: totalChunks > 0 ? Math.round(totalWords / totalChunks) : 0,
          averageChunksPerUrl: Object.keys(urlStats).length > 0 
            ? Math.round(totalChunks / Object.keys(urlStats).length) 
            : 0,
          urlStats
        }
      };

    } catch (error) {
      console.error('Error getting chunk stats:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Delete all chunks for a URL
   */
  async deleteChunks(clientId, url) {
    try {
      const { error } = await supabase
        .from('content_chunks')
        .delete()
        .eq('client_id', clientId)
        .eq('url', url);

      if (error) throw error;

      console.log(`🗑️ Deleted chunks for ${url}`);
      return { success: true };

    } catch (error) {
      console.error('Error deleting chunks:', error);
      return { success: false, error: error.message };
    }
  }
}

export default new ChunkingService();
