// Code Generated by Sidekick is for learning and experimentation purposes only.

import crypto from 'crypto';

/**
 * Generate a unique API key
 * Format: greeto-{32-char-hex}
 * Example: greeto-a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
 */
export function generateApiKey() {
  const randomBytes = crypto.randomBytes(16);
  const randomString = randomBytes.toString('hex');
  return `greeto-${randomString}`;
}

/**
 * Validate API key format
 */
export function isValidApiKeyFormat(apiKey) {
  return /^greeto-[a-f0-9]{32}$/.test(apiKey);
}
