// Code Generated by Sidekick is for learning and experimentation purposes only.

/**
 * Generate embed script for a client
 * @param {string} apiKey - Client's API key
 * @returns {string} Complete embed script HTML
 */
export function generateEmbedScript(apiKey) {
  const widgetUrl = process.env.WIDGET_URL || 'http://localhost:3000/widget.js';
  
  return `<script src="${widgetUrl}" data-api-key="${apiKey}"></script>`;
}

/**
 * Generate installation instructions
 */
export function generateInstallInstructions(apiKey) {
  const script = generateEmbedScript(apiKey);
  
  return {
    embed_script: script,
    instructions: [
      '1. Copy the script below',
      '2. Paste it before the closing </body> tag in your website',
      '3. The chat widget will appear automatically'
    ],
    example: `
<!DOCTYPE html>
<html>
<head>
  <title>Your Website</title>
</head>
<body>
  <!-- Your content -->
  
  <!-- Greeto Chat Widget -->
  ${script}
</body>
</html>
    `.trim()
  };
}
