// Code Generated by Sidekick is for learning and experimentation purposes only.

import 'dotenv/config';
import express from 'express';
import cors from 'cors';

// Import routes
import chatRoutes from './routes/chatRoutes.js';
import scraperRoutes from './routes/scraperRoutes.js';
import embeddingRoutes from './routes/embeddingRoutes.js';
import searchRoutes from './routes/searchRoutes.js';
import widgetRoutes from './routes/widgetRoutes.js';      // ✅ NEW
import adminRoutes from './routes/adminRoutes.js';        // ✅ NEW

// Import middleware
import { apiKeyMiddleware } from './middleware/apiKey.js';
import './config/database.js';

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok', message: 'Server is running' });
});

// Widget config endpoint (NO apiKeyMiddleware - validates internally)
app.use('/api/widget', widgetRoutes);

// Admin endpoints (NO auth for now - add later)
app.use('/api/admin', adminRoutes);

// Existing API routes (with apiKeyMiddleware)
app.use('/api/chat', apiKeyMiddleware, chatRoutes);
app.use('/api/scraper', apiKeyMiddleware, scraperRoutes);
app.use('/api/embeddings', apiKeyMiddleware, embeddingRoutes);
app.use('/api/search', apiKeyMiddleware, searchRoutes);

// Error handling middleware
app.use((err, req, res, next) => {
  console.error('Error:', err);
  res.status(500).json({ error: 'Something went wrong!' });
});

// Start server
const PORT = process.env.PORT || 5001;
app.listen(PORT, () => {
  console.log(`\n🚀 Server running on port ${PORT}`);
  console.log(`📊 Health check: http://localhost:${PORT}/health`);
  console.log(`🎨 Widget config: http://localhost:${PORT}/api/widget/config`);
  console.log(`👨‍💼 Admin panel: http://localhost:${PORT}/api/admin/clients\n`);
});
