// Code Generated by Sidekick is for learning and experimentation purposes only.

import 'dotenv/config';
import express from 'express';
import cors from 'cors';

// Import routes
import chatRoutes from './routes/chatRoutes.js';
import scraperRoutes from './routes/scraperRoutes.js';
import embeddingRoutes from './routes/embeddingRoutes.js';
import searchRoutes from './routes/searchRoutes.js';
import widgetRoutes from './routes/widgetRoutes.js';      // ✅ API-key based
import adminRoutes from './routes/adminRoutes.js';        // ✅ Dashboard protected routes
import authRoutes from './routes/authRoutes.js';          // ✅ NEW: /api/me
import clientRoutes from './routes/clientRoutes.js';      // ✅ NEW: /api/client/* protected

// Import middleware
import { apiKeyMiddleware } from './middleware/apiKey.js';
import { requireDashboardAuth, requireDashboardRole } from './middleware/dashboardAuth.js';
import './config/database.js';

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok', message: 'Server is running' });
});

// ============================================
// Dashboard Authentication Routes
// ============================================

// GET /api/me - Check dashboard access (requires valid token, no role restriction)
app.use('/api', authRoutes);

// Protected Admin Routes: /api/admin/*
// Requires: valid Bearer token + super_admin role
// RLS enforced on all queries via req.supabaseClient
app.use('/api/admin', requireDashboardAuth, requireDashboardRole(['super_admin']), adminRoutes);

// Protected Client Routes: /api/client/*
// Requires: valid Bearer token + client role
// RLS enforced on all queries via req.supabaseClient
app.use('/api/client', requireDashboardAuth, requireDashboardRole(['client']), clientRoutes);

// ============================================
// Widget & API-Key Based Routes (unchanged)
// ============================================

// Widget config endpoint (NO dashboard auth - validates via API key)
app.use('/api/widget', widgetRoutes);

// ============================================
// Legacy API Routes (with apiKeyMiddleware)
// ============================================
app.use('/api/chat', apiKeyMiddleware, chatRoutes);
app.use('/api/scraper', apiKeyMiddleware, scraperRoutes);
app.use('/api/embeddings', apiKeyMiddleware, embeddingRoutes);
app.use('/api/search', apiKeyMiddleware, searchRoutes);

// Error handling middleware
app.use((err, req, res, next) => {
  console.error('Error:', err);
  res.status(500).json({ error: 'Something went wrong!' });
});

// Start server
const PORT = process.env.PORT || 5001;
app.listen(PORT, () => {
  console.log(`\n🚀 Server running on port ${PORT}`);
  console.log(`📊 Health check: http://localhost:${PORT}/health`);
  console.log(`🎨 Widget config: http://localhost:${PORT}/api/widget/config`);
  console.log(`👨‍💼 Admin panel: http://localhost:${PORT}/api/admin/clients\n`);
});
